	soc_system u0 (
		.cam_controller_d5m_d                  (<connected-to-cam_controller_d5m_d>),                  //               cam_controller.d5m_d
		.cam_controller_d5m_fval               (<connected-to-cam_controller_d5m_fval>),               //                             .d5m_fval
		.cam_controller_d5m_lval               (<connected-to-cam_controller_d5m_lval>),               //                             .d5m_lval
		.cam_controller_d5m_pixclk             (<connected-to-cam_controller_d5m_pixclk>),             //                             .d5m_pixclk
		.cam_controller_d5m_reset_n            (<connected-to-cam_controller_d5m_reset_n>),            //                             .d5m_reset_n
		.cam_controller_debug_addressupdate    (<connected-to-cam_controller_debug_addressupdate>),    //                             .debug_addressupdate
		.cam_controller_debug_linefifoclear    (<connected-to-cam_controller_debug_linefifoclear>),    //                             .debug_linefifoclear
		.cam_controller_debug_linefiforr       (<connected-to-cam_controller_debug_linefiforr>),       //                             .debug_linefiforr
		.cam_controller_debug_linefifowreq     (<connected-to-cam_controller_debug_linefifowreq>),     //                             .debug_linefifowreq
		.cam_controller_debug_pixfiforreq      (<connected-to-cam_controller_debug_pixfiforreq>),      //                             .debug_pixfiforreq
		.cam_controller_debug_burstcountmaster (<connected-to-cam_controller_debug_burstcountmaster>), //                             .debug_burstcountmaster
		.cam_controller_debug_byteenablemaster (<connected-to-cam_controller_debug_byteenablemaster>), //                             .debug_byteenablemaster
		.cam_controller_debug_waitreqmaster    (<connected-to-cam_controller_debug_waitreqmaster>),    //                             .debug_waitreqmaster
		.cam_controller_debug_writemaster      (<connected-to-cam_controller_debug_writemaster>),      //                             .debug_writemaster
		.cam_controller_debug_addressmaster    (<connected-to-cam_controller_debug_addressmaster>),    //                             .debug_addressmaster
		.cam_controller_debug_pixfifoaclr      (<connected-to-cam_controller_debug_pixfifoaclr>),      //                             .debug_pixfifoaclr
		.cam_controller_debug_pixfifordusedw   (<connected-to-cam_controller_debug_pixfifordusedw>),   //                             .debug_pixfifordusedw
		.cam_controller_debug_pixfifowreq      (<connected-to-cam_controller_debug_pixfifowreq>),      //                             .debug_pixfifowreq
		.cam_controller_debug_writedatamaster  (<connected-to-cam_controller_debug_writedatamaster>),  //                             .debug_writedatamaster
		.cam_controller_debug_linefifodata     (<connected-to-cam_controller_debug_linefifodata>),     //                             .debug_linefifodata
		.cam_controller_debug_pixfifodata      (<connected-to-cam_controller_debug_pixfifodata>),      //                             .debug_pixfifodata
		.cam_controller_debug_linestate        (<connected-to-cam_controller_debug_linestate>),        //                             .debug_linestate
		.cam_controller_debug_pixelstate       (<connected-to-cam_controller_debug_pixelstate>),       //                             .debug_pixelstate
		.cam_controller_debug_offset           (<connected-to-cam_controller_debug_offset>),           //                             .debug_offset
		.clk_clk                               (<connected-to-clk_clk>),                               //                          clk.clk
		.hps_0_ddr_mem_a                       (<connected-to-hps_0_ddr_mem_a>),                       //                    hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                      (<connected-to-hps_0_ddr_mem_ba>),                      //                             .mem_ba
		.hps_0_ddr_mem_ck                      (<connected-to-hps_0_ddr_mem_ck>),                      //                             .mem_ck
		.hps_0_ddr_mem_ck_n                    (<connected-to-hps_0_ddr_mem_ck_n>),                    //                             .mem_ck_n
		.hps_0_ddr_mem_cke                     (<connected-to-hps_0_ddr_mem_cke>),                     //                             .mem_cke
		.hps_0_ddr_mem_cs_n                    (<connected-to-hps_0_ddr_mem_cs_n>),                    //                             .mem_cs_n
		.hps_0_ddr_mem_ras_n                   (<connected-to-hps_0_ddr_mem_ras_n>),                   //                             .mem_ras_n
		.hps_0_ddr_mem_cas_n                   (<connected-to-hps_0_ddr_mem_cas_n>),                   //                             .mem_cas_n
		.hps_0_ddr_mem_we_n                    (<connected-to-hps_0_ddr_mem_we_n>),                    //                             .mem_we_n
		.hps_0_ddr_mem_reset_n                 (<connected-to-hps_0_ddr_mem_reset_n>),                 //                             .mem_reset_n
		.hps_0_ddr_mem_dq                      (<connected-to-hps_0_ddr_mem_dq>),                      //                             .mem_dq
		.hps_0_ddr_mem_dqs                     (<connected-to-hps_0_ddr_mem_dqs>),                     //                             .mem_dqs
		.hps_0_ddr_mem_dqs_n                   (<connected-to-hps_0_ddr_mem_dqs_n>),                   //                             .mem_dqs_n
		.hps_0_ddr_mem_odt                     (<connected-to-hps_0_ddr_mem_odt>),                     //                             .mem_odt
		.hps_0_ddr_mem_dm                      (<connected-to-hps_0_ddr_mem_dm>),                      //                             .mem_dm
		.hps_0_ddr_oct_rzqin                   (<connected-to-hps_0_ddr_oct_rzqin>),                   //                             .oct_rzqin
		.hps_0_io_hps_io_emac1_inst_TX_CLK     (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CLK>),     //                     hps_0_io.hps_io_emac1_inst_TX_CLK
		.hps_0_io_hps_io_emac1_inst_TXD0       (<connected-to-hps_0_io_hps_io_emac1_inst_TXD0>),       //                             .hps_io_emac1_inst_TXD0
		.hps_0_io_hps_io_emac1_inst_TXD1       (<connected-to-hps_0_io_hps_io_emac1_inst_TXD1>),       //                             .hps_io_emac1_inst_TXD1
		.hps_0_io_hps_io_emac1_inst_TXD2       (<connected-to-hps_0_io_hps_io_emac1_inst_TXD2>),       //                             .hps_io_emac1_inst_TXD2
		.hps_0_io_hps_io_emac1_inst_TXD3       (<connected-to-hps_0_io_hps_io_emac1_inst_TXD3>),       //                             .hps_io_emac1_inst_TXD3
		.hps_0_io_hps_io_emac1_inst_RXD0       (<connected-to-hps_0_io_hps_io_emac1_inst_RXD0>),       //                             .hps_io_emac1_inst_RXD0
		.hps_0_io_hps_io_emac1_inst_MDIO       (<connected-to-hps_0_io_hps_io_emac1_inst_MDIO>),       //                             .hps_io_emac1_inst_MDIO
		.hps_0_io_hps_io_emac1_inst_MDC        (<connected-to-hps_0_io_hps_io_emac1_inst_MDC>),        //                             .hps_io_emac1_inst_MDC
		.hps_0_io_hps_io_emac1_inst_RX_CTL     (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CTL>),     //                             .hps_io_emac1_inst_RX_CTL
		.hps_0_io_hps_io_emac1_inst_TX_CTL     (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CTL>),     //                             .hps_io_emac1_inst_TX_CTL
		.hps_0_io_hps_io_emac1_inst_RX_CLK     (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CLK>),     //                             .hps_io_emac1_inst_RX_CLK
		.hps_0_io_hps_io_emac1_inst_RXD1       (<connected-to-hps_0_io_hps_io_emac1_inst_RXD1>),       //                             .hps_io_emac1_inst_RXD1
		.hps_0_io_hps_io_emac1_inst_RXD2       (<connected-to-hps_0_io_hps_io_emac1_inst_RXD2>),       //                             .hps_io_emac1_inst_RXD2
		.hps_0_io_hps_io_emac1_inst_RXD3       (<connected-to-hps_0_io_hps_io_emac1_inst_RXD3>),       //                             .hps_io_emac1_inst_RXD3
		.hps_0_io_hps_io_sdio_inst_CMD         (<connected-to-hps_0_io_hps_io_sdio_inst_CMD>),         //                             .hps_io_sdio_inst_CMD
		.hps_0_io_hps_io_sdio_inst_D0          (<connected-to-hps_0_io_hps_io_sdio_inst_D0>),          //                             .hps_io_sdio_inst_D0
		.hps_0_io_hps_io_sdio_inst_D1          (<connected-to-hps_0_io_hps_io_sdio_inst_D1>),          //                             .hps_io_sdio_inst_D1
		.hps_0_io_hps_io_sdio_inst_CLK         (<connected-to-hps_0_io_hps_io_sdio_inst_CLK>),         //                             .hps_io_sdio_inst_CLK
		.hps_0_io_hps_io_sdio_inst_D2          (<connected-to-hps_0_io_hps_io_sdio_inst_D2>),          //                             .hps_io_sdio_inst_D2
		.hps_0_io_hps_io_sdio_inst_D3          (<connected-to-hps_0_io_hps_io_sdio_inst_D3>),          //                             .hps_io_sdio_inst_D3
		.hps_0_io_hps_io_usb1_inst_D0          (<connected-to-hps_0_io_hps_io_usb1_inst_D0>),          //                             .hps_io_usb1_inst_D0
		.hps_0_io_hps_io_usb1_inst_D1          (<connected-to-hps_0_io_hps_io_usb1_inst_D1>),          //                             .hps_io_usb1_inst_D1
		.hps_0_io_hps_io_usb1_inst_D2          (<connected-to-hps_0_io_hps_io_usb1_inst_D2>),          //                             .hps_io_usb1_inst_D2
		.hps_0_io_hps_io_usb1_inst_D3          (<connected-to-hps_0_io_hps_io_usb1_inst_D3>),          //                             .hps_io_usb1_inst_D3
		.hps_0_io_hps_io_usb1_inst_D4          (<connected-to-hps_0_io_hps_io_usb1_inst_D4>),          //                             .hps_io_usb1_inst_D4
		.hps_0_io_hps_io_usb1_inst_D5          (<connected-to-hps_0_io_hps_io_usb1_inst_D5>),          //                             .hps_io_usb1_inst_D5
		.hps_0_io_hps_io_usb1_inst_D6          (<connected-to-hps_0_io_hps_io_usb1_inst_D6>),          //                             .hps_io_usb1_inst_D6
		.hps_0_io_hps_io_usb1_inst_D7          (<connected-to-hps_0_io_hps_io_usb1_inst_D7>),          //                             .hps_io_usb1_inst_D7
		.hps_0_io_hps_io_usb1_inst_CLK         (<connected-to-hps_0_io_hps_io_usb1_inst_CLK>),         //                             .hps_io_usb1_inst_CLK
		.hps_0_io_hps_io_usb1_inst_STP         (<connected-to-hps_0_io_hps_io_usb1_inst_STP>),         //                             .hps_io_usb1_inst_STP
		.hps_0_io_hps_io_usb1_inst_DIR         (<connected-to-hps_0_io_hps_io_usb1_inst_DIR>),         //                             .hps_io_usb1_inst_DIR
		.hps_0_io_hps_io_usb1_inst_NXT         (<connected-to-hps_0_io_hps_io_usb1_inst_NXT>),         //                             .hps_io_usb1_inst_NXT
		.hps_0_io_hps_io_spim1_inst_CLK        (<connected-to-hps_0_io_hps_io_spim1_inst_CLK>),        //                             .hps_io_spim1_inst_CLK
		.hps_0_io_hps_io_spim1_inst_MOSI       (<connected-to-hps_0_io_hps_io_spim1_inst_MOSI>),       //                             .hps_io_spim1_inst_MOSI
		.hps_0_io_hps_io_spim1_inst_MISO       (<connected-to-hps_0_io_hps_io_spim1_inst_MISO>),       //                             .hps_io_spim1_inst_MISO
		.hps_0_io_hps_io_spim1_inst_SS0        (<connected-to-hps_0_io_hps_io_spim1_inst_SS0>),        //                             .hps_io_spim1_inst_SS0
		.hps_0_io_hps_io_uart0_inst_RX         (<connected-to-hps_0_io_hps_io_uart0_inst_RX>),         //                             .hps_io_uart0_inst_RX
		.hps_0_io_hps_io_uart0_inst_TX         (<connected-to-hps_0_io_hps_io_uart0_inst_TX>),         //                             .hps_io_uart0_inst_TX
		.hps_0_io_hps_io_i2c0_inst_SDA         (<connected-to-hps_0_io_hps_io_i2c0_inst_SDA>),         //                             .hps_io_i2c0_inst_SDA
		.hps_0_io_hps_io_i2c0_inst_SCL         (<connected-to-hps_0_io_hps_io_i2c0_inst_SCL>),         //                             .hps_io_i2c0_inst_SCL
		.hps_0_io_hps_io_i2c1_inst_SDA         (<connected-to-hps_0_io_hps_io_i2c1_inst_SDA>),         //                             .hps_io_i2c1_inst_SDA
		.hps_0_io_hps_io_i2c1_inst_SCL         (<connected-to-hps_0_io_hps_io_i2c1_inst_SCL>),         //                             .hps_io_i2c1_inst_SCL
		.hps_0_io_hps_io_gpio_inst_GPIO09      (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO09>),      //                             .hps_io_gpio_inst_GPIO09
		.hps_0_io_hps_io_gpio_inst_GPIO35      (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO35>),      //                             .hps_io_gpio_inst_GPIO35
		.hps_0_io_hps_io_gpio_inst_GPIO40      (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO40>),      //                             .hps_io_gpio_inst_GPIO40
		.hps_0_io_hps_io_gpio_inst_GPIO53      (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO53>),      //                             .hps_io_gpio_inst_GPIO53
		.hps_0_io_hps_io_gpio_inst_GPIO54      (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO54>),      //                             .hps_io_gpio_inst_GPIO54
		.hps_0_io_hps_io_gpio_inst_GPIO61      (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO61>),      //                             .hps_io_gpio_inst_GPIO61
		.i2c_0_i2c_scl                         (<connected-to-i2c_0_i2c_scl>),                         //                    i2c_0_i2c.scl
		.i2c_0_i2c_sda                         (<connected-to-i2c_0_i2c_sda>),                         //                             .sda
		.pio_leds_external_connection_export   (<connected-to-pio_leds_external_connection_export>),   // pio_leds_external_connection.export
		.pll_0_outclk0_clk                     (<connected-to-pll_0_outclk0_clk>),                     //                pll_0_outclk0.clk
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //                        reset.reset_n
		.pll_0_locked_export                   (<connected-to-pll_0_locked_export>)                    //                 pll_0_locked.export
	);

